version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: make dev
    ports:
      - "8080:8080"
    image: swoushtein/devops-for-programmers-project-74:latest
