name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      # Устанавливаем Docker и Docker Compose
      - name: Set up Docker Buildx (for Docker Compose support)
        uses: docker/setup-buildx-action@v2

      # Проверяем установку Docker и Docker Compose
      - name: Check Docker Compose version
        run: docker-compose version

      - name: Install dependencies
        run: npm install

      - name: Run tests with Docker Compose
        run: docker-compose -f docker-compose.yml run app npm test

      - name: Build Docker image
        run: docker build -f Dockerfile.production -t swoushtein/devops-for-programmers-project-74:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: docker push swoushtein/devops-for-programmers-project-74:latest



